initial version
pebble-examples/feature-content-size pull request #1
Opened 2016-09-30 22:44 UTC by orviwan

2016-10-05 07:30 UTC, cjwilliams requested changes

2016-10-05 07:30 UTC, cjwilliams commented on README.md
> +[ContentSize Documentation](https://developer.pebble.com/docs/c/)
Maybe link directly to the ContentSize docs once you know the URL?

2016-10-05 07:30 UTC, cjwilliams commented on src/content_size.c
> +    case NumPreferredContentSizes:
default?

2016-10-05 07:30 UTC, cjwilliams commented on wscript
> +        ctx.set_env(ctx.all_envs[p])
This is an old wscript, do not use it

2016-10-05 09:01 UTC, orviwan commented
Ready for another review @cjwilliams

2016-10-05 18:11 UTC, cjwilliams approved these changes

2016-10-07 13:08 UTC, martijnthe commented
Does it make sense to also add a Rocky.js example in this repo?
In terms of "finding your way" in the examples, I think it makes sense to have both Rocky+C in the same repo. It's also a good way to lure C devs into trying Rocky if they haven't already :D

2016-10-07 20:31 UTC, merged